[window]
opacity=0.8
decorations="none"

[font]
size = 10.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
bright_foreground = "#fbf1c7"

[colors.normal]
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
