[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
